#!/usr/bin/env python3
"""Check Cowok.ai I-Wish -> Codex project skill bridge drift."""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except Exception:  # pragma: no cover - PyYAML is optional for this utility.
    yaml = None

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n?", re.S)
SOURCE_RE = re.compile(r"Generated by sync-codex-skill-bridges\.py; source=([^;]+); kind=([^ ]+) -->")


def find_project_root(start: Path | None = None) -> Path:
    current = (start or Path.cwd()).resolve()
    while current != current.parent:
        if (current / ".agent").exists() and (current / ".agents").exists():
            return current
        current = current.parent
    return (start or Path.cwd()).resolve()


def parse_frontmatter(path: Path) -> dict[str, str]:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return {}
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}
    if yaml is not None:
        try:
            loaded = yaml.safe_load(match.group(1)) or {}
            if isinstance(loaded, dict):
                return {str(key): str(value) for key, value in loaded.items() if value is not None}
        except Exception:
            pass
    data: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if ":" not in line or line.lstrip().startswith("#"):
            continue
        key, value = line.split(":", 1)
        data[key.strip()] = value.strip().strip("\"'")
    return data


def iter_skill_files(root: Path):
    for skill_dir in [root / ".agent" / "skills", root / ".agent" / "generated-skills"]:
        if not skill_dir.exists():
            continue
        for path in sorted(skill_dir.rglob("SKILL.md")):
            if any(part in {"node_modules", "__pycache__"} for part in path.parts):
                continue
            yield path


def collect_source_names(root: Path) -> dict[str, str]:
    sources: dict[str, tuple[int, str]] = {}

    def add(name: str, priority: int, source: str) -> None:
        old = sources.get(name)
        if old is None or priority > old[0]:
            sources[name] = (priority, source)

    for path in sorted((root / ".agent" / "workflows").glob("*.md")):
        if path.is_file():
            add(path.stem, 30, path.relative_to(root).as_posix())
    for path in sorted((root / ".agent" / "agents").glob("*.md")):
        if path.is_file():
            add(path.stem, 20, path.relative_to(root).as_posix())
    for path in iter_skill_files(root):
        add(path.parent.name, 10, path.relative_to(root).as_posix())
    return {name: source for name, (_, source) in sources.items()}


def check(root: Path) -> dict:
    sources = collect_source_names(root)
    dest_root = root / ".agents" / "skills"
    bridges = {path.parent.name: path for path in dest_root.glob("*/SKILL.md") if path.is_file()}
    missing = sorted(set(sources) - set(bridges))
    invalid_frontmatter = []
    broken_generated_refs = []

    for name, path in sorted(bridges.items()):
        fm = parse_frontmatter(path)
        if not fm.get("name") or not fm.get("description"):
            invalid_frontmatter.append({"name": name, "path": path.relative_to(root).as_posix()})
        text = path.read_text(encoding="utf-8", errors="replace")
        marker = SOURCE_RE.search(text)
        if marker:
            source_rel = marker.group(1)
            if not (root / source_rel).exists():
                broken_generated_refs.append({"name": name, "bridge": path.relative_to(root).as_posix(), "source": source_rel})

    return {
        "checked_at": datetime.now(timezone.utc).isoformat(),
        "project_root": str(root),
        "sources_total": len(sources),
        "project_codex_skills_total": len(bridges),
        "missing": missing,
        "invalid_frontmatter": invalid_frontmatter,
        "broken_generated_refs": broken_generated_refs,
        "ok": not missing and not invalid_frontmatter and not broken_generated_refs,
    }


def write_report(root: Path, report: dict) -> None:
    evidence_dir = root / "_iwish-output" / "evidence"
    evidence_dir.mkdir(parents=True, exist_ok=True)
    path = evidence_dir / "cowok-codex-bridge-drift-check.json"
    path.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Check Cowok.ai Codex project skill bridge drift.")
    parser.add_argument("--root", type=Path, default=None, help="Cowok.ai repository root. Defaults to nearest repo with .agent and .agents.")
    parser.add_argument("--no-write-report", action="store_true", help="Do not write evidence JSON.")
    args = parser.parse_args()

    root = (args.root or find_project_root()).resolve()
    report = check(root)
    if not args.no_write_report:
        write_report(root, report)
    print(json.dumps(report, indent=2, ensure_ascii=False))
    return 0 if report["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
