#!/usr/bin/env bash

IWISH_RUNTIME_MAPPINGS=(
  "_iwish/core/tasks/workflow.xml|.agent/workflows/workflow-engine.xml|core engine|copy"
  "_iwish/delivery/workflows/4-implementation/make-story/workflow.yaml|.agent/workflows/iwish-feature-create-story.md|workflow config|manifest:make-story"
  "_iwish/delivery/workflows/4-implementation/review/workflow.yaml|.agent/workflows/iwish-feature-code-review.md|workflow config|manifest:review"
  "_iwish/delivery/workflows/4-implementation/code/workflow.yaml|.agent/workflows/iwish-feature-dev-story.md|workflow config|manifest:code"
  "_iwish/delivery/workflows/4-implementation/sprint-planning/workflow.yaml|.agent/workflows/iwish-feature-sprint-planning.md|workflow config|manifest:sprint-planning"
  "_iwish/delivery/workflows/4-implementation/status/workflow.yaml|.agent/workflows/iwish-feature-sprint-status.md|workflow config|manifest:status"
  "_iwish/delivery/workflows/4-implementation/correct-course/workflow.yaml|.agent/workflows/iwish-feature-correct-course.md|workflow config|manifest:correct-course"
  "_iwish/delivery/workflows/4-implementation/retro/workflow.yaml|.agent/workflows/iwish-feature-retrospective.md|workflow config|manifest:retro"
  "_iwish/delivery/workflows/4-implementation/make-data-spec/workflow.yaml|.agent/workflows/make-data-spec.md|workflow config|manifest:make-data-spec"
  "_iwish/delivery/workflows/4-implementation/make-ui-spec/workflow.yaml|.agent/workflows/make-ui-spec.md|workflow config|manifest:make-ui-spec"
  "_iwish/delivery/workflows/4-implementation/canary/workflow.yaml|.agent/workflows/canary.md|workflow config|manifest:canary"
)

LEGACY_BMAD_RUNTIME_MAPPINGS=(
  "_iwish/core/tasks/workflow.xml|.agent/workflows/workflow-engine.xml|core engine|copy"
  "_iwish/bmm/workflows/4-implementation/create-story/workflow.yaml|.agent/workflows/iwish-feature-create-story.md|workflow config|manifest:create-story"
  "_iwish/bmm/workflows/4-implementation/code-review/workflow.yaml|.agent/workflows/iwish-feature-code-review.md|workflow config|manifest:code-review"
  "_iwish/bmm/workflows/4-implementation/Vegeta-story/workflow.yaml|.agent/workflows/iwish-feature-dev-story.md|workflow config|manifest:Vegeta-story"
  "_iwish/bmm/workflows/4-implementation/sprint-planning/workflow.yaml|.agent/workflows/iwish-feature-sprint-planning.md|workflow config|manifest:sprint-planning"
  "_iwish/bmm/workflows/4-implementation/sprint-status/workflow.yaml|.agent/workflows/iwish-feature-sprint-status.md|workflow config|manifest:sprint-status"
  "_iwish/bmm/workflows/4-implementation/correct-course/workflow.yaml|.agent/workflows/iwish-feature-correct-course.md|workflow config|manifest:correct-course"
  "_iwish/bmm/workflows/4-implementation/retrospective/workflow.yaml|.agent/workflows/iwish-feature-retrospective.md|workflow config|manifest:retrospective"
)

runtime_mappings_print() {
  local namespace="$1"

  case "$namespace" in
    iwish)
      printf '%s\n' "${IWISH_RUNTIME_MAPPINGS[@]}"
      ;;
    legacy-iwish|iwish)
      printf '%s\n' "${LEGACY_BMAD_RUNTIME_MAPPINGS[@]}"
      ;;
    *)
      echo "Unknown runtime namespace: $namespace" >&2
      return 2
      ;;
  esac
}

runtime_make_manifest() {
  local namespace="$1"
  local name="$2"
  local source_wrapper="$3"
  local temp="$4"
  local runtime_root installed_path runtime_engine

  if [[ "$namespace" == "iwish" ]]; then
    runtime_root="_iwish"
    installed_path="{project-root}/_iwish/delivery/workflows/4-implementation/$name"
    runtime_engine="{project-root}/_iwish/core/tasks/workflow.xml"
  else
    runtime_root="_bmad"
    installed_path="{project-root}/_iwish/bmm/workflows/4-implementation/$name"
    runtime_engine="{project-root}/_iwish/core/tasks/workflow.xml"
  fi

  cat > "$temp" <<EOF
# Generated by .agent/scripts/materialize-iwish-runtime.sh
name: "$name"
runtime_kind: "wrapper-config"
source_wrapper: "{project-root}/$source_wrapper"
source_mode_engine: "{project-root}/.agent/workflows/workflow-engine.xml"
project_runtime_engine: "$runtime_engine"
installed_path: "$installed_path"
instructions: "{project-root}/$source_wrapper"
template: false
source_mode_fallback: true
compatibility:
  canonical_namespace: "$namespace"
  legacy_runtime_root: "_bmad"
execution:
  mode: "wrapper-backed"
  contract: "Load project_runtime_engine, then load this config, then load source_wrapper and execute its steps."
notes:
  - "This config is executable by the I-Wish generic workflow engine as a wrapper-backed workflow."
  - "Legacy I-Wish wrappers remain supported through compatibility aliases."
  - "If a richer workflow.yaml exists in a distribution package, install it over this generated config with explicit approval."
EOF
}

iwish_runtime_generate_expected() {
  local runtime="$1"
  local source="$2"
  local materialization="$3"
  local temp="$4"
  local namespace="${5:-legacy-iwish}"

  if [[ "$materialization" == "copy" ]]; then
    cp "$source" "$temp"
    return 0
  fi

  if [[ "$materialization" == manifest:* ]]; then
    local name="${materialization#manifest:}"
    runtime_make_manifest "$namespace" "$name" "$source" "$temp"
    return 0
  fi

  echo "Unknown materialization strategy for $runtime: $materialization" >&2
  return 2
}

iwish_runtime_status() {
  local runtime="$1"
  local source="$2"
  local materialization="$3"
  local temp="$4"
  local namespace="${5:-legacy-iwish}"

  if [[ ! -f "$runtime" ]]; then
    if [[ -f "$source" ]]; then
      echo "template-only"
    else
      echo "missing"
    fi
    return 0
  fi

  if [[ ! -f "$source" ]]; then
    echo "missing"
    return 0
  fi

  iwish_runtime_generate_expected "$runtime" "$source" "$materialization" "$temp" "$namespace"
  if cmp -s "$runtime" "$temp"; then
    echo "materialized"
  else
    echo "conflict"
  fi
}
