#!/usr/bin/env python3
"""Synchronize Cowok.ai I-Wish capabilities into Codex-visible project skills.

This is project-local only. It reads Cowok.ai's `.agent/...` capability sources
and materializes lightweight bridge skills under `.agents/skills/<name>/SKILL.md`.
It never reads from or writes to the upstream I-Wish checkout and never writes to
`~/.codex`.
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

try:
    import yaml
except Exception:  # pragma: no cover - PyYAML is optional for this utility.
    yaml = None

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n?", re.S)
GENERATED_MARKER = "Generated by sync-codex-skill-bridges.py"


@dataclass(frozen=True)
class CapabilitySource:
    name: str
    kind: str
    path: Path
    description: str
    priority: int


def find_project_root(start: Path | None = None) -> Path:
    current = (start or Path.cwd()).resolve()
    while current != current.parent:
        if (current / ".agent").exists() and (current / ".agents").exists():
            return current
        current = current.parent
    return (start or Path.cwd()).resolve()


def parse_frontmatter(path: Path) -> dict[str, str]:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return {}
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}
    if yaml is not None:
        try:
            loaded = yaml.safe_load(match.group(1)) or {}
            if isinstance(loaded, dict):
                return {str(key): str(value) for key, value in loaded.items() if value is not None}
        except Exception:
            pass
    data: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if ":" not in line or line.lstrip().startswith("#"):
            continue
        key, value = line.split(":", 1)
        data[key.strip()] = value.strip().strip("\"'")
    return data


def yaml_quote(value: str) -> str:
    compact = " ".join((value or "").split())
    return '"' + compact.replace("\\", "\\\\").replace('"', '\\"') + '"'


def iter_skill_files(root: Path) -> Iterable[Path]:
    for skill_dir in [root / ".agent" / "skills", root / ".agent" / "generated-skills"]:
        if not skill_dir.exists():
            continue
        for path in sorted(skill_dir.rglob("SKILL.md")):
            if any(part in {"node_modules", "__pycache__"} for part in path.parts):
                continue
            yield path


def collect_sources(root: Path) -> tuple[dict[str, CapabilitySource], dict[str, list[CapabilitySource]]]:
    sources: dict[str, CapabilitySource] = {}
    duplicates: dict[str, list[CapabilitySource]] = {}

    def add(name: str, kind: str, path: Path, priority: int) -> None:
        fm = parse_frontmatter(path)
        description = fm.get("description") or f"Run Cowok.ai I-Wish {name} {kind}"
        source = CapabilitySource(name=name, kind=kind, path=path, description=description, priority=priority)
        old = sources.get(name)
        if old:
            duplicates.setdefault(name, [old]).append(source)
            if priority <= old.priority:
                return
        sources[name] = source

    for path in sorted((root / ".agent" / "workflows").glob("*.md")):
        if path.is_file():
            add(path.stem, "workflow", path, 30)
    for path in sorted((root / ".agent" / "agents").glob("*.md")):
        if path.is_file():
            add(path.stem, "agent", path, 20)
    for path in iter_skill_files(root):
        add(path.parent.name, "skill", path, 10)

    return sources, duplicates


def bridge_content(root: Path, source: CapabilitySource) -> str:
    rel = source.path.relative_to(root).as_posix()
    source_dir = source.path.parent.relative_to(root).as_posix()
    return """---
name: {name}
description: {description}
---
<!-- {marker}; source={source_rel}; kind={kind} -->
[Cowok.ai I-Wish {kind_title}: {name}]
You are running within the Cowok.ai project-local I-Wish framework.
Determine the current repository root first. Prefer the source file at `{source_rel}` inside the current repository root. If it is not present, use this fallback source file: {root}/{source_rel}
You MUST read, adhere to, and strictly execute the instructions defined in that {kind} file.
Do NOT skip steps.

Resolve all relative paths from the source directory `{source_dir}` in the current repository root.
Input Context/Arguments: $ARGUMENTS
""".format(
        name=source.name,
        description=yaml_quote(source.description),
        marker=GENERATED_MARKER,
        source_rel=rel,
        kind=source.kind,
        kind_title=source.kind.title(),
        source_dir=source_dir,
        root=root,
    )


def sync(root: Path, *, update_existing_generated: bool, dry_run: bool) -> dict:
    sources, duplicates = collect_sources(root)
    dest_root = root / ".agents" / "skills"
    created: list[dict] = []
    updated: list[dict] = []
    skipped_existing: list[str] = []

    for name, source in sorted(sources.items()):
        dest = dest_root / name / "SKILL.md"
        content = bridge_content(root, source)
        if dest.exists():
            existing = dest.read_text(encoding="utf-8", errors="replace")
            if GENERATED_MARKER in existing and existing != content and update_existing_generated:
                if not dry_run:
                    dest.write_text(content, encoding="utf-8")
                updated.append({"name": name, "kind": source.kind, "source": source.path.relative_to(root).as_posix()})
            else:
                skipped_existing.append(name)
            continue
        if not dry_run:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(content, encoding="utf-8")
        created.append({"name": name, "kind": source.kind, "source": source.path.relative_to(root).as_posix()})

    post = {path.parent.name for path in dest_root.glob("*/SKILL.md") if path.is_file()}
    missing = sorted(set(sources) - post)
    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "project_root": str(root),
        "sources_total": len(sources),
        "project_codex_skills_total": len(post),
        "created": created,
        "updated": updated,
        "skipped_existing": skipped_existing,
        "missing_after": missing,
        "duplicates": {
            name: [
                {"kind": item.kind, "source": item.path.relative_to(root).as_posix(), "priority": item.priority}
                for item in items
            ]
            for name, items in sorted(duplicates.items())
        },
        "dry_run": dry_run,
    }
    return report


def write_reports(root: Path, report: dict) -> None:
    evidence_dir = root / "_iwish-output" / "evidence"
    evidence_dir.mkdir(parents=True, exist_ok=True)
    json_path = evidence_dir / "cowok-codex-skill-bridge-sync.json"
    txt_path = evidence_dir / "cowok-codex-skill-bridge-sync.txt"
    json_path.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    lines = [
        "Cowok.ai Codex skill bridge sync",
        f"project_root={report['project_root']}",
        f"sources_total={report['sources_total']}",
        f"project_codex_skills_total={report['project_codex_skills_total']}",
        f"created={len(report['created'])}",
        f"updated={len(report['updated'])}",
        f"skipped_existing={len(report['skipped_existing'])}",
        f"missing_after={len(report['missing_after'])}",
        "",
        "created:",
    ]
    lines += [f"  {item['name']}: {item['kind']} -> {item['source']}" for item in report["created"]]
    lines += ["", "updated:"]
    lines += [f"  {item['name']}: {item['kind']} -> {item['source']}" for item in report["updated"]]
    lines += ["", "missing_after:"]
    lines += [f"  {name}" for name in report["missing_after"]]
    lines += ["", "duplicate_names:"]
    for name, items in report["duplicates"].items():
        chosen = max(items, key=lambda item: item["priority"])
        lines.append(f"  {name}: chosen {chosen['kind']} -> {chosen['source']}")
    txt_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync Cowok.ai I-Wish capabilities into project-local Codex skills.")
    parser.add_argument("--root", type=Path, default=None, help="Cowok.ai repository root. Defaults to nearest repo with .agent and .agents.")
    parser.add_argument("--dry-run", action="store_true", help="Report changes without writing bridge files.")
    parser.add_argument("--update-existing-generated", action="store_true", default=True, help="Refresh bridge files generated by this script.")
    parser.add_argument("--no-update-existing-generated", action="store_false", dest="update_existing_generated", help="Do not refresh generated bridge files.")
    args = parser.parse_args()

    root = (args.root or find_project_root()).resolve()
    report = sync(root, update_existing_generated=args.update_existing_generated, dry_run=args.dry_run)
    if not args.dry_run:
        write_reports(root, report)
    print(json.dumps({
        "project_root": report["project_root"],
        "sources_total": report["sources_total"],
        "created": len(report["created"]),
        "updated": len(report["updated"]),
        "skipped_existing": len(report["skipped_existing"]),
        "missing_after": len(report["missing_after"]),
        "dry_run": report["dry_run"],
    }, indent=2, ensure_ascii=False))
    return 1 if report["missing_after"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
